name: cuda-env-py39
channels:
        - nvidia/label/cuda-11.5.2
        - nvidia/label/cuda-11.5.1
        - nvidia/label/cuda-11.5.0
        - nvidia
        - rapidsai
        - conda-forge
        - bioconda
        - defaults
dependencies:
        - cuda=11.5
        - cuda-nvcc=11.5
        - cuda-python=11.5
        - cudnn=8.2
        - cudatoolkit=11.5
        - rapids=22.04
        - rmm
        - conda-forge::cupy=9*
        - h5py
        - python-graphviz
        - graphviz
        - python-snappy
        - snappy
        # specific version required for glmnet, but looks like we can have libgfortran5 installed simultaneously?
        - libgfortran4
